### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by underr** [phikal/4jhan-server#4]
Needs some work.
When accessing some thread that doesn't exist anymore:

```
TypeError: Cannot set property 'thread' of undefined
    at Statement.<anonymous> (/home/under/4jhan-server/lib/sqlite.js:49:21)
--> in Database#all('SELECT * FROM comment WHERE op = ?', '1', [Function])
    at Statement.<anonymous> (/home/under/4jhan-server/lib/sqlite.js:47:8)
```

**Comment by phikal** [comment]
Submitted a fix to `testing`. Seems to work.

**Comment by underr** [comment]
Oh nice, closing this one
